### ISSUE TITLE
Does not work in node 4.6.0 LTS

### ISSUE THREAD

**Issue by silkimen** [thenativeweb/eslint-config-es#1]
Hey guys :)

latest version 0.8.5 doesn't work on node 4.6.0, which is the current LTS version. It's caused by the array prototype function call `includes` in lines [289](https://github.com/thenativeweb/eslint-config-es/blob/master/2015/server.js#L289), [293] (https://github.com/thenativeweb/eslint-config-es/blob/master/2015/server.js#L293) and [312] (https://github.com/thenativeweb/eslint-config-es/blob/master/2015/server.js#L312). This is not supported in node 4.6.0.

Would you mind changing this to support older node versions? I would suggest adding an polyfill or just using old fashioned `indexOf` call.

**Comment by goloroden** [comment]
Thanks for reporting this issue :-)

With respect to the fact that Node.js 6.x will become the new LTS *this month*, how important is this for you?

**Comment by silkimen** [comment]
Well, actually I didn't know that :)
But unfortunately I think it will take some time, until everyone switches to the new LTS version. So I think it would be nice to support older versions. But it's up to you, I can downgrade the package as a workaround. If you don't mind, I think you should at at least add an info text claiming it's only supported on node >= 6.0

**Comment by goloroden** [comment]
No problem. The Node.js documentation features some documentation on the [LTS roadmap](https://github.com/nodejs/LTS).

Apart from that, I decided to use a polyfill. Could you please verify whether the code [in this PR](https://github.com/thenativeweb/eslint-config-es/pull/2) works for you on Node.js 4?

**Comment by silkimen** [comment]
Yap, this one is working flawlessly, thanks! 👍

**Comment by goloroden** [comment]
Great, I'm then merging the PR and am going to release a new version soon.
