### ISSUE TITLE
linebreak-style

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [thenativeweb/eslint-config-es#392]
Ich verwende das Paket in einem Projekt mit Vue.js & TypeScript. IDE ist PHPStorm. Projekt hat keine Verbindung zu einem GitHub-Repository.

Unter Windows 10 erhalte ich die Fehlermeldungen, wenn ich den Befehl "npm run analyse" ausführe.

`export default interface Comment {

    id: number;
    body: string;
    postId: number;

}
`

![linebreak-style](https://user-images.githubusercontent.com/7149991/128422306-781c6603-766c-4b92-9973-3a660176cbcb.PNG)

**Comment by goloroden** [comment]
As already discussed on Discord, this is by design.

Having consistent line breaks in a project independent of which type of line breaks a developer uses, is preferred from our POV.
