### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by ghost** [thenativeweb/eslint-config-es#4]
Hi Golo,

your config causes linter warnings:

`(node:21951) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "es/2015/client")
`

due to https://github.com/thenativeweb/eslint-config-es/search?q=parserOptions.ecmaFeatures.experimentalObjectRestSpread&unscoped_q=parserOptions.ecmaFeatures.experimentalObjectRestSpread

**Comment by goloroden** [comment]
Hi @stefanheine 😊 

Yes, this line currently causes a problem.

The reason for this is that we do not update `eslint-config-es` every time a new version of ESLint gets released. We only do this from time to time as part of [roboter](https://www.npmjs.com/package/roboter). If you use the ESLint version of roboter, things should match each other without any problems.

Nevertheless, we should update the rules sooner or later again, and then this issue will be gone. Right now, there is not yet a need for this.

Is there a special reason for you to use a newer ESLint version than the one from roboter?

**Comment by goloroden** [comment]
This should not be relevant any more for the current build, hence closed.
